# Makefile for Example 2
LTX = latex
L2H2 = latex2html -init_file myinit.pl -info "External_links_test"

ex2 :   ex21.aux ex22.aux
    $(L2H2) ex2bib ex21 ex22 ex20
ex21.aux :
	 $(LTX) ex21.tex
ex22.aux :
	 $(LTX) ex22.tex
