$pdf_mode = 4;

$bibtex_use = 1;
$bibtex = 'biber %O %B';

$makeindex = 'xindex -c letgut -l "*"';

$quote_filenames = 0;

$clean_ext .= ' synctex.gz* run.xml tex.bak out sta bbl bcf fdb_latexmk run tdo
    listing *~ lo* xdy vrb ain atfi nav snm thm iny xref db* listing tcbtemp aux
    idx ind lof lot out toc acn acr alg glg* glo* gls* ins sbl slg sym ist
    run.xml xdy lol fls unq synctex.gz mw *~ aux bcf frm msk nlg nls ntn tcbtemp
    thm nav nlo not idx ilg ind lof lot out toc acn acr alg glg glo gls glg2 gls2
    glo2 sbl slg slo sls sym glsdefs ist run.xml xdy lol fls unq synctex.gz *~
    listing png tkzfct.gnuplot tkzfct.table mw snm tns sta vrb xref 4ct 4tc idv
    lg pre tmp *.typo upa' ;

@generated_exts = qw(db* listing tcbtemp aux idx ind lof lot out toc acn acr alg
glg* glo* gls* ins sbl slg sym ist run.xml xdy lol fls unq synctex.gz mw *~ aux
bcf frm msk nlg nls ntn tcbtemp thm nav nlo not i dx ind lof lot out toc acn acr
alg glg glo gls glg2 gls2 glo2 sbl slg slo sls sym glsdefs ist run.xml xdy lol
fls unq synctex.gz *~ listing png tkzfct.gnuplot tkzfct.table mw snm tns sta
vrb xref *.typo upa);

push @generated_exts, 'acn', 'acr', 'alg', 'bcf', 'fls', 'gl*', 'sbl*', 'sl*', 'sym*' ;

