#!/bin/sh
#    Copyright (C) 1991 Silvio Levy
#     
#    This file is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This file is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# In this script "$@" stands for the set of arguments passed to the
# script, as expanded by the UNIX shell; these arguments are passed,
# without further expansion, to `makefont'.  For examply, typing
#
# makeall boo
#
# to the UNIX shell has the same effect as typing
#
# makefont grreg10 boo
# makefont grreg8 boo
# makefont grbld10 boo
# makefont grtt10 boo
     
makefont grreg10 "$@"
makefont grreg8 "$@"
makefont grbld10 "$@"
makefont grtt10 "$@"
