#!/bin/sh
#    Copyright (C) 1991 Silvio Levy
#     
#    This file is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This file is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# In this script $# stands for the number of arguments, not including the
# command name.  $0 is the command name, $1 the first argument, and so
# on.  For instance, typing
#
# makefont grreg10 alw 1
#
# to the UNIX shell gives the same result as typing
#
# cmmf '\mode:=alw;mag:=magstep(1);batchmode;input grreg10'
     
case $# in
0) echo $0 source [ mode [ mag ]];;
1) cmmf '\mode:=localmode;batchmode;input '$1;;
2) cmmf '\mode:='$2';batchmode;input '$1;;
3) cmmf '\mode:='$2';mag:=magstep('$3');batchmode;input '$1;;
esac
