#!/bin/sh
#    Copyright (C) 1991 Silvio Levy
#     
#    This file is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This file is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# In this script $1 stands for the first argument passed to the
# script.  The three lines preceding EOF are passed as standard
# input to the program called on the first line.  For example,
# typing
#
# testfont foo
#
# to the UNIX shell has the same effect as typing
#
# tex grtestfont                %this line is read by the shell
# foo                           %these three lines are read by TeX
# \bigtest
# \end
# mv grtestfont.dvi foo.dvi     %this is again read by the shell
#
# mv means move, or rename.
#
     
tex grtestfont << EOF
$1
\bigtest
\end
EOF
mv grtestfont.dvi $1.dvi
