#! /bin/csh -xv
# Test LaTeX des cesures appliquees sur le site sur plus de 500 mots
# et comparaison avec avec la liste ideale des coupures.   maj --bg 2000/02/18

echo "latex lgencoup >/dev/null"
      latex lgencoup >/dev/null
if (`grep -e "-51- ERREUR" lgencoup.log`) then
  echo "-51- ERREUR le document n'a pas ete converti en 8-bits"
  exit
endif

# to avoid finding ^ instead of \^
sed -e 's/\^\^\[/\\oe\{\}\{\}/g' <lgencoup.log | sed -e 's/\^a/\\\^a/g'  -e 's/\^e/\\\^e/g' -e 's/\^i/\\\^\\i/g' -e 's/\^o/\\\^o/g' -e 's/\^u/\\\^u/g' -e 's/\^A/\\\^A/g' -e 's/\^E/\\\^E/g' -e 's/\^I/\\\^I/g' -e 's/\^O/\\\^O/g' -e 's/\^U/\\\^U/g' >myhyph.log

latex ltstcoup
rm ltstcoup.dvi 
rm lgencoup.aux
mv ltstcoup.log ltesthyp.log 
rm lgencoup.log
rm ltstcoup.idx myhyph.log
###########
#%%
#%%      checksum        = "52841 25 117 836"
#%%
