#! /bin/csh 
# Test TeX des cesures appliquees sur le site sur plus de 500 mots
# et comparaison avec avec la liste ideale des coupures.    maj --bg 2000/02/18

echo "tex gencoup >/dev/null"
      tex gencoup >/dev/null
if (`grep -e "-51- ERREUR" gencoup.log`) then
  echo "-51- ERREUR le document n'a pas ete converti en 8-bits"
  exit
endif

# to avoid finding ^ instead of \^
sed -e 's/\^\^\[/\\oe\{\}\{\}/g' <gencoup.log | sed -e 's/\^a/\\\^a/g'  -e 's/\^e/\\\^e/g' -e 's/\^i/\\\^\\i/g' -e 's/\^o/\\\^o/g' -e 's/\^u/\\\^u/g' -e 's/\^A/\\\^A/g' -e 's/\^E/\\\^E/g' -e 's/\^I/\\\^I/g' -e 's/\^O/\\\^O/g' -e 's/\^U/\\\^U/g' >myhyph.log

tex tstcoup
rm tstcoup.dvi 
mv tstcoup.log testhyp.log
rm gencoup.log
rm tstcoup.idx myhyph.log
###########
#%%
#%%      checksum        = "46975 24 113 799"
#%%
